<?php
/**
 * PDF compliance report exporter.
 *
 * @package TaxPilot\Export
 */

declare( strict_types=1 );

namespace TaxPilot\Export;

use TaxPilot\Database\RatesTable;

/**
 * Exports tax rates as a PDF compliance report.
 * Requires the Dompdf library (composer require dompdf/dompdf).
 */
class PDFExporter {

	/**
	 * Check if PDF export is available.
	 *
	 * @return bool
	 */
	public static function is_available(): bool {
		return class_exists( '\\Dompdf\\Dompdf' );
	}

	/**
	 * Generate and output a PDF file.
	 */
	public function export(): void {
		if ( ! self::is_available() ) {
			wp_die(
				esc_html__( 'PDF export requires the Dompdf library. Run: composer require dompdf/dompdf', 'taxpilot' ),
				esc_html__( 'PDF Export Unavailable', 'taxpilot' ),
				[ 'response' => 503 ]
			);
		}

		$rates = RatesTable::get_all( [ 'limit' => 10000 ] );
		$html  = $this->generate_html( $rates );

		$dompdf = new \Dompdf\Dompdf();
		$dompdf->loadHtml( $html );
		$dompdf->setPaper( 'A4', 'landscape' );
		$dompdf->render();

		$filename = 'taxpilot-compliance-report-' . gmdate( 'Y-m-d' ) . '.pdf';
		$dompdf->stream( $filename, [ 'Attachment' => true ] );
	}

	/**
	 * Generate HTML for the PDF.
	 *
	 * @param array $rates Rate data.
	 * @return string HTML content.
	 */
	private function generate_html( array $rates ): string {
		$date = wp_date( 'F j, Y' );

		$html = '<!DOCTYPE html><html><head><style>
			body { font-family: sans-serif; font-size: 12px; color: #333; }
			h1 { color: #4f46e5; font-size: 24px; margin-bottom: 5px; }
			.subtitle { color: #6b7280; margin-bottom: 20px; }
			table { width: 100%; border-collapse: collapse; margin-top: 20px; }
			th { background: #4f46e5; color: #fff; padding: 8px; text-align: left; font-size: 10px; text-transform: uppercase; }
			td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; font-size: 11px; }
			tr:nth-child(even) td { background: #f9fafb; }
			.footer { margin-top: 30px; font-size: 10px; color: #9ca3af; text-align: center; }
		</style></head><body>';

		$html .= '<h1>TaxPilot for WooCommerce — Tax Compliance Report</h1>';
		$html .= '<p class="subtitle">Generated on ' . esc_html( $date ) . ' | Total rates: ' . count( $rates ) . '</p>';

		$html .= '<table><thead><tr>';
		$html .= '<th>Country</th><th>State</th><th>Rate %</th><th>Name</th><th>Type</th><th>Class</th><th>Source</th><th>Updated</th>';
		$html .= '</tr></thead><tbody>';

		foreach ( $rates as $rate ) {
			$html .= '<tr>';
			$html .= '<td>' . esc_html( $rate['country_code'] ) . '</td>';
			$html .= '<td>' . esc_html( $rate['state'] ) . '</td>';
			$html .= '<td>' . esc_html( $rate['rate'] ) . '%</td>';
			$html .= '<td>' . esc_html( $rate['rate_name'] ) . '</td>';
			$html .= '<td>' . esc_html( $rate['rate_type'] ) . '</td>';
			$html .= '<td>' . esc_html( $rate['tax_class'] ?: 'Standard' ) . '</td>';
			$html .= '<td>' . esc_html( $rate['source'] ) . '</td>';
			$html .= '<td>' . esc_html( $rate['updated_at'] ) . '</td>';
			$html .= '</tr>';
		}

		$html .= '</tbody></table>';
		$html .= '<p class="footer">This report was auto-generated by TaxPilot for WooCommerce. It is for informational purposes only and does not constitute tax advice.</p>';
		$html .= '</body></html>';

		return $html;
	}
}
