/**
 * TaxPilot for WooCommerce — Shared constants.
 */

export const REST_NAMESPACE = 'taxpilot/v1';

export const WIZARD_STEPS = [
	{ key: 'store-setup', label: 'Store Setup', number: 1 },
	{ key: 'product-types', label: 'Product Types', number: 2 },
	{ key: 'target-countries', label: 'Countries', number: 3 },
	{ key: 'preview-rates', label: 'Preview Rates', number: 4 },
	{ key: 'apply-rates', label: 'Apply', number: 5 },
];

export const PRODUCT_TYPES = [
	{
		value: 'physical',
		label: 'Physical Goods',
		description: 'Tangible products shipped to customers.',
	},
	{
		value: 'digital',
		label: 'Digital Goods',
		description: 'Downloads, software, e-books, online courses.',
	},
	{
		value: 'services',
		label: 'Services',
		description: 'Consulting, freelancing, SaaS subscriptions.',
	},
];

export const REGION_PRESETS = {
	eu: {
		label: 'European Union',
		countries: [
			'AT',
			'BE',
			'BG',
			'HR',
			'CY',
			'CZ',
			'DK',
			'EE',
			'FI',
			'FR',
			'DE',
			'GR',
			'HU',
			'IE',
			'IT',
			'LV',
			'LT',
			'LU',
			'MT',
			'NL',
			'PL',
			'PT',
			'RO',
			'SK',
			'SI',
			'ES',
			'SE',
		],
	},
	north_america: {
		label: 'North America',
		countries: [ 'US', 'CA', 'MX' ],
	},
	apac: {
		label: 'Asia-Pacific',
		countries: [ 'AU', 'NZ', 'JP', 'SG', 'IN', 'KR', 'TH', 'MY', 'PH' ],
	},
	uk: {
		label: 'United Kingdom',
		countries: [ 'GB' ],
	},
};

export const COUNTRIES = {
	US: 'United States',
	CA: 'Canada',
	MX: 'Mexico',
	GB: 'United Kingdom',
	DE: 'Germany',
	FR: 'France',
	IT: 'Italy',
	ES: 'Spain',
	NL: 'Netherlands',
	BE: 'Belgium',
	AT: 'Austria',
	PT: 'Portugal',
	IE: 'Ireland',
	SE: 'Sweden',
	DK: 'Denmark',
	FI: 'Finland',
	PL: 'Poland',
	CZ: 'Czech Republic',
	RO: 'Romania',
	HU: 'Hungary',
	GR: 'Greece',
	BG: 'Bulgaria',
	HR: 'Croatia',
	SK: 'Slovakia',
	SI: 'Slovenia',
	LT: 'Lithuania',
	LV: 'Latvia',
	EE: 'Estonia',
	LU: 'Luxembourg',
	MT: 'Malta',
	CY: 'Cyprus',
	AU: 'Australia',
	NZ: 'New Zealand',
	JP: 'Japan',
	IN: 'India',
	SG: 'Singapore',
	KR: 'South Korea',
	TH: 'Thailand',
	MY: 'Malaysia',
	PH: 'Philippines',
	CH: 'Switzerland',
	NO: 'Norway',
	IS: 'Iceland',
	ZA: 'South Africa',
	BR: 'Brazil',
	TR: 'Turkey',
	AE: 'United Arab Emirates',
	SA: 'Saudi Arabia',
};

export const CURRENCIES = {
	USD: 'US Dollar',
	EUR: 'Euro',
	GBP: 'British Pound',
	CAD: 'Canadian Dollar',
	AUD: 'Australian Dollar',
	NZD: 'New Zealand Dollar',
	JPY: 'Japanese Yen',
	INR: 'Indian Rupee',
	SGD: 'Singapore Dollar',
	CHF: 'Swiss Franc',
	SEK: 'Swedish Krona',
	NOK: 'Norwegian Krone',
	DKK: 'Danish Krone',
	PLN: 'Polish Zloty',
	CZK: 'Czech Koruna',
	HUF: 'Hungarian Forint',
	RON: 'Romanian Leu',
	BGN: 'Bulgarian Lev',
	HRK: 'Croatian Kuna',
	BRL: 'Brazilian Real',
	MXN: 'Mexican Peso',
	ZAR: 'South African Rand',
	TRY: 'Turkish Lira',
	AED: 'UAE Dirham',
	SAR: 'Saudi Riyal',
	KRW: 'South Korean Won',
	THB: 'Thai Baht',
	MYR: 'Malaysian Ringgit',
	PHP: 'Philippine Peso',
	ISK: 'Icelandic Króna',
};
